https://parallelum.com.br/fipe/api/v1/carros/marcas/59/modelos/5940/anos/2014-3

###

#GET: https://paralelum.com.br/fipe/api/v1/carros/marcas/59/modelos

###

#https://parallelum.com.br/fipe/api/v1/carros/marcas

###

#https://paralelum.com.br/fipe/api/v1/motos/marcas
